// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

/*
Package workerpb is a generated protocol buffer package.

It is generated from these files:
	worker.proto

It has these top-level messages:
	Worker
*/
package workerpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Worker struct {
	Source    uint32 `protobuf:"varint,1,opt,name=source" json:"source,omitempty"`
	Stepcount uint64 `protobuf:"varint,2,opt,name=stepcount" json:"stepcount,omitempty"`
	VertexID  uint64 `protobuf:"varint,3,opt,name=vertexID" json:"vertexID,omitempty"`
	MsgValue  []byte `protobuf:"bytes,4,opt,name=msgValue,proto3" json:"msgValue,omitempty"`
}

func (m *Worker) Reset()                    { *m = Worker{} }
func (m *Worker) String() string            { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()               {}
func (*Worker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Worker) GetSource() uint32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *Worker) GetStepcount() uint64 {
	if m != nil {
		return m.Stepcount
	}
	return 0
}

func (m *Worker) GetVertexID() uint64 {
	if m != nil {
		return m.VertexID
	}
	return 0
}

func (m *Worker) GetMsgValue() []byte {
	if m != nil {
		return m.MsgValue
	}
	return nil
}

func init() {
	proto.RegisterType((*Worker)(nil), "workerpb.Worker")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xcf, 0x2f, 0xca,
	0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf0, 0x0a, 0x92, 0x94, 0xca,
	0xb8, 0xd8, 0xc2, 0xc1, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x28, 0x4f, 0x48, 0x86, 0x8b, 0xb3, 0xb8, 0x24, 0xb5, 0x20,
	0x39, 0xbf, 0x34, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0x21, 0x20, 0x24, 0xc5,
	0xc5, 0x51, 0x96, 0x5a, 0x54, 0x92, 0x5a, 0xe1, 0xe9, 0x22, 0xc1, 0x0c, 0x96, 0x84, 0xf3, 0x41,
	0x72, 0xb9, 0xc5, 0xe9, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41,
	0x70, 0x7e, 0x12, 0x1b, 0xd8, 0x21, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0xc3, 0xa6,
	0x76, 0x98, 0x00, 0x00, 0x00,
}
