// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Superstep.proto

/*
Package superstep is a generated protocol buffer package.

It is generated from these files:
	Superstep.proto

It has these top-level messages:
	Vertex
	Superstep
*/
package superstep

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Superstep_Command int32

const (
	Superstep_START      Superstep_Command = 0
	Superstep_RUN        Superstep_Command = 1
	Superstep_ACK        Superstep_Command = 2
	Superstep_VOTETOHALT Superstep_Command = 3
)

var Superstep_Command_name = map[int32]string{
	0: "START",
	1: "RUN",
	2: "ACK",
	3: "VOTETOHALT",
}
var Superstep_Command_value = map[string]int32{
	"START":      0,
	"RUN":        1,
	"ACK":        2,
	"VOTETOHALT": 3,
}

func (x Superstep_Command) String() string {
	return proto.EnumName(Superstep_Command_name, int32(x))
}
func (Superstep_Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Vertex struct {
	Id    uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Vertex) Reset()                    { *m = Vertex{} }
func (m *Vertex) String() string            { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()               {}
func (*Vertex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vertex) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vertex) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Superstep struct {
	Source          uint32            `protobuf:"varint,1,opt,name=source" json:"source,omitempty"`
	Command         Superstep_Command `protobuf:"varint,2,opt,name=command,enum=superstep.Superstep_Command" json:"command,omitempty"`
	Stepcount       uint64            `protobuf:"varint,3,opt,name=stepcount" json:"stepcount,omitempty"`
	DatasetFilename string            `protobuf:"bytes,4,opt,name=datasetFilename" json:"datasetFilename,omitempty"`
	Application     string            `protobuf:"bytes,5,opt,name=application" json:"application,omitempty"`
	Vertices        []*Vertex         `protobuf:"bytes,6,rep,name=vertices" json:"vertices,omitempty"`
	StartVertex     uint32            `protobuf:"varint,7,opt,name=startVertex" json:"startVertex,omitempty"`
}

func (m *Superstep) Reset()                    { *m = Superstep{} }
func (m *Superstep) String() string            { return proto.CompactTextString(m) }
func (*Superstep) ProtoMessage()               {}
func (*Superstep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Superstep) GetSource() uint32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *Superstep) GetCommand() Superstep_Command {
	if m != nil {
		return m.Command
	}
	return Superstep_START
}

func (m *Superstep) GetStepcount() uint64 {
	if m != nil {
		return m.Stepcount
	}
	return 0
}

func (m *Superstep) GetDatasetFilename() string {
	if m != nil {
		return m.DatasetFilename
	}
	return ""
}

func (m *Superstep) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Superstep) GetVertices() []*Vertex {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *Superstep) GetStartVertex() uint32 {
	if m != nil {
		return m.StartVertex
	}
	return 0
}

func init() {
	proto.RegisterType((*Vertex)(nil), "superstep.Vertex")
	proto.RegisterType((*Superstep)(nil), "superstep.Superstep")
	proto.RegisterEnum("superstep.Superstep_Command", Superstep_Command_name, Superstep_Command_value)
}

func init() { proto.RegisterFile("Superstep.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x2b, 0x3b, 0xb1, 0xeb, 0x0b, 0x4d, 0xdc, 0xa3, 0x14, 0x0d, 0x19, 0x4c, 0x26, 0x2f,
	0xf5, 0x90, 0x42, 0xf6, 0x10, 0x5a, 0x0a, 0x2d, 0x0d, 0x28, 0x6e, 0x76, 0xd5, 0xd6, 0x20, 0x48,
	0x2c, 0x23, 0xc9, 0xa1, 0xbf, 0xb2, 0xbf, 0xa9, 0x58, 0x4e, 0x1c, 0xd3, 0x4d, 0xf7, 0xdd, 0xbb,
	0xd3, 0x7b, 0x12, 0xcc, 0x76, 0x4d, 0x2d, 0xb4, 0xb1, 0xa2, 0xce, 0x6a, 0xad, 0xac, 0xc2, 0xc8,
	0x5c, 0xc0, 0x22, 0x83, 0x60, 0x2f, 0xb4, 0x15, 0x3f, 0x38, 0x05, 0x4f, 0x96, 0x94, 0x24, 0x24,
	0x1d, 0x31, 0x4f, 0x96, 0xf8, 0x00, 0xe3, 0x13, 0x3f, 0x34, 0x82, 0x7a, 0x09, 0x49, 0x09, 0xeb,
	0x8a, 0xc5, 0xaf, 0x07, 0x51, 0xbf, 0x0e, 0x1f, 0x21, 0x30, 0xaa, 0xd1, 0x85, 0x70, 0x73, 0x77,
	0xec, 0x5c, 0xe1, 0x0a, 0xc2, 0x42, 0x1d, 0x8f, 0xbc, 0x2a, 0xdd, 0xf4, 0x74, 0x39, 0xcf, 0xfa,
	0x2b, 0xb3, 0xab, 0x9b, 0x4d, 0xa7, 0x61, 0x17, 0x31, 0xce, 0x21, 0x6a, 0x1b, 0x85, 0x6a, 0x2a,
	0x4b, 0x7d, 0x67, 0xe5, 0x0a, 0x30, 0x85, 0x59, 0xc9, 0x2d, 0x37, 0xc2, 0xbe, 0xca, 0x83, 0xa8,
	0xf8, 0x51, 0xd0, 0x51, 0x42, 0xd2, 0x88, 0xfd, 0xc7, 0x98, 0xc0, 0x84, 0xd7, 0xf5, 0x41, 0x16,
	0xdc, 0x4a, 0x55, 0xd1, 0xb1, 0x53, 0x0d, 0x11, 0x3e, 0xc1, 0xed, 0x49, 0x68, 0x2b, 0x0b, 0x61,
	0x68, 0x90, 0xf8, 0xe9, 0x64, 0x79, 0x3f, 0xb0, 0xd8, 0x3d, 0x09, 0xeb, 0x25, 0xed, 0x42, 0x63,
	0xb9, 0xb6, 0x5d, 0x83, 0x86, 0x2e, 0xed, 0x10, 0x2d, 0x56, 0x10, 0x9e, 0xe3, 0x60, 0x04, 0xe3,
	0x5d, 0xbe, 0x66, 0x79, 0x7c, 0x83, 0x21, 0xf8, 0xec, 0xeb, 0x33, 0x26, 0xed, 0x61, 0xbd, 0x79,
	0x8f, 0x3d, 0x9c, 0x02, 0xec, 0xb7, 0xf9, 0x4b, 0xbe, 0x7d, 0x5b, 0x7f, 0xe4, 0xb1, 0xff, 0x1d,
	0xb8, 0x2f, 0x79, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x33, 0xdc, 0x70, 0xb9, 0xa5, 0x01, 0x00,
	0x00,
}
